name: tdxhydrorapid
channels:
- conda-forge
- defaults
dependencies:
  - python>=3.11
  - geopandas>=1.0
  - netcdf4
  - numpy
  - pandas
  - shapely>=2
  - pyproj
  - dask
  - xarray
  - scikit-learn